"""
build_lineage_page.py — Generate lineage.html (the skill "origin story" viz).

Embeds data/lineage.json into a standalone D3 page with two views:
  1. Timeline — each copied-skill cluster as a row; dots are repos placed at
     their first-commit date; the earliest (ancestor) is ringed and linked to
     each descendant. Reads as skills being born, then copied later.
  2. Sankey — ancestor repo -> descendant repo copy flows (who originates vs
     who copies), weighted by number of skills.
Plus a call-out of non-obvious ancestors (small origin, big descendant).

Usage:  python crawlers/build_lineage_page.py
"""
import json
from pathlib import Path

BASE = Path(__file__).parent.parent
LIN = BASE / 'data' / 'lineage.json'
OUT = BASE / 'lineage.html'

TEMPLATE = """<!DOCTYPE html>
<html lang="en"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>Skill Lineage — the Origin Story</title>
<script src="https://cdn.jsdelivr.net/npm/d3@7"></script>
<script src="https://cdn.jsdelivr.net/npm/d3-sankey@0.12"></script>
<style>
:root{--bg:#f9f8f6;--bg2:#f2f1ee;--ink:#111110;--dim:#5a5850;--faint:#a8a59c;--border:#dddbd6;--accent:#16a34a;--alert:#d94f2a;--mono:'DM Mono',ui-monospace,monospace;--sans:'Barlow',system-ui,sans-serif;}
*{box-sizing:border-box;}
body{margin:0;background:var(--bg);color:var(--ink);font-family:var(--sans);}
header{padding:22px 28px 10px;border-bottom:1px solid var(--border);}
h1{margin:0;font-size:22px;letter-spacing:-.01em;}
.sub{color:var(--dim);font-size:13px;margin-top:5px;max-width:760px;line-height:1.5;}
.sub a{color:var(--accent);}
.tabs{display:flex;gap:6px;padding:14px 28px 0;}
.tab{font-family:var(--mono);font-size:11px;letter-spacing:.06em;text-transform:uppercase;padding:7px 13px;border:1px solid var(--border);border-radius:5px 5px 0 0;background:var(--bg2);cursor:pointer;color:var(--dim);}
.tab.on{background:#fff;color:var(--ink);border-bottom-color:#fff;font-weight:600;}
.panel{display:none;padding:18px 28px 40px;}
.panel.on{display:block;}
.stat{display:inline-block;margin:0 26px 10px 0;}
.stat b{font-size:26px;font-family:var(--mono);}
.stat span{display:block;font-size:11px;color:var(--dim);text-transform:uppercase;letter-spacing:.06em;}
.callout{background:#fff;border:1px solid var(--border);border-left:3px solid var(--alert);border-radius:6px;padding:14px 16px;margin:6px 0 18px;max-width:900px;}
.callout h3{margin:0 0 8px;font-size:13px;text-transform:uppercase;letter-spacing:.06em;color:var(--alert);}
.callout .row{font-size:13px;margin:5px 0;}
.callout code{font-family:var(--mono);background:var(--bg2);padding:1px 5px;border-radius:3px;}
svg{background:#fff;border:1px solid var(--border);border-radius:6px;}
.tip{position:fixed;pointer-events:none;background:#111;color:#fff;font-family:var(--mono);font-size:11px;padding:6px 9px;border-radius:4px;opacity:0;max-width:320px;line-height:1.4;}
text{font-family:var(--mono);}
footer{padding:18px 28px 40px;color:var(--faint);font-size:12px;}
footer a{color:var(--accent);}
</style></head><body>
<header>
  <h1>Skill Lineage — the Origin Story</h1>
  <div class="sub">Where copied skills actually come from. We clustered
  near-identical SKILL.md files across __NREPOS__ crawled repos, then used each
  copy's first git-commit date to find its <b>ancestor</b> — the repo it appeared
  in earliest — and the descendants that copied it. <a href="https://github.com/dhk/skill-map/blob/main/docs/llm-judge-tuning.md" target="_blank">Method &amp; the bulk-publish finding →</a></div>
</header>
<div class="tabs">
  <div class="tab on" data-p="time">Timeline</div>
  <div class="tab" data-p="sankey">Copy flows</div>
</div>
<div id="time" class="panel on">
  <div>
    <div class="stat"><b id="s-clusters">0</b><span>copied-skill clusters</span></div>
    <div class="stat"><b id="s-skills">0</b><span>duplicate copies</span></div>
    <div class="stat"><b id="s-flows">0</b><span>repo→repo copy flows</span></div>
  </div>
  <div id="nonobvious"></div>
  <svg id="timeline"></svg>
</div>
<div id="sankey" class="panel">
  <div class="sub" style="margin:0 0 12px">Left = where a skill was first committed (ancestor). Right = repos that later carried a copy. Thickness = number of skills.</div>
  <svg id="sankeysvg"></svg>
</div>
<footer>Generated by <code style="font-family:var(--mono)">crawlers/lineage_trace.py</code> + <code style="font-family:var(--mono)">build_lineage_page.py</code>. First-commit dates via the GitHub commits API. <a href="index.html">← back to the map</a></footer>
<div class="tip" id="tip"></div>
<script>
const LINEAGE = __DATA__;
const tip=document.getElementById('tip');
function showTip(html,x,y){tip.innerHTML=html;tip.style.opacity=1;tip.style.left=(x+12)+'px';tip.style.top=(y+12)+'px';}
function hideTip(){tip.style.opacity=0;}
document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{
  document.querySelectorAll('.tab').forEach(x=>x.classList.remove('on'));
  document.querySelectorAll('.panel').forEach(x=>x.classList.remove('on'));
  t.classList.add('on');document.getElementById(t.dataset.p).classList.add('on');
  if(t.dataset.p==='sankey') drawSankey();
});

// only clusters with a resolved ancestor date
const clusters=LINEAGE.clusters.filter(c=>c.ancestor && c.ancestor.first_date)
  .map(c=>({...c, members:c.members.filter(m=>m.first_date)}))
  .sort((a,b)=>new Date(a.ancestor.first_date)-new Date(b.ancestor.first_date));
document.getElementById('s-clusters').textContent=clusters.length;
document.getElementById('s-skills').textContent=LINEAGE.clusters.reduce((s,c)=>s+c.members.length,0);
document.getElementById('s-flows').textContent=LINEAGE.flows.length;

// non-obvious ancestors callout
if(LINEAGE.nonobvious && LINEAGE.nonobvious.length){
  const el=document.getElementById('nonobvious');
  el.innerHTML='<div class="callout"><h3>Non-obvious ancestors — small origin, big spread</h3>'
    + LINEAGE.nonobvious.slice(0,6).map(n=>`<div class="row">⤷ <code>${n.skill}</code> first appeared in <code>${n.ancestor_repo}</code> (${n.ancestor_stars||0}★) — later copied into <code>${n.biggest_descendant}</code> (${(n.descendant_stars||0).toLocaleString()}★)</div>`).join('')
    + '</div>';
}

// ---- Timeline ----
(function drawTimeline(){
  const rowH=15, top=30, left=230, right=40;
  const W=Math.max(900, (document.body.clientWidth||1000)-56);
  const H=top+clusters.length*rowH+40;
  const svg=d3.select('#timeline').attr('width',W).attr('height',H);
  const dates=clusters.flatMap(c=>c.members.map(m=>new Date(m.first_date)));
  const x=d3.scaleTime().domain(d3.extent(dates)).range([left, W-right]);
  svg.append('g').attr('transform',`translate(0,${top-8})`).call(d3.axisTop(x).ticks(8))
     .selectAll('text').attr('font-size',10);
  const repos=[...new Set(clusters.flatMap(c=>c.members.map(m=>m.repo)))];
  const color=d3.scaleOrdinal(d3.schemeTableau10.concat(d3.schemeSet3)).domain(repos);
  const row=svg.selectAll('.row').data(clusters).join('g')
    .attr('transform',(d,i)=>`translate(0,${top+i*rowH})`);
  row.append('text').attr('x',left-8).attr('y',4).attr('text-anchor','end')
     .attr('font-size',9).attr('fill','#333').text(d=>d.skill.slice(0,30));
  row.each(function(d){
    const g=d3.select(this);
    const xs=d.members.map(m=>x(new Date(m.first_date)));
    g.append('line').attr('x1',Math.min(...xs)).attr('x2',Math.max(...xs))
      .attr('y1',0).attr('y2',0).attr('stroke','#ccc').attr('stroke-width',1);
    g.selectAll('circle').data(d.members).join('circle')
      .attr('cx',m=>x(new Date(m.first_date))).attr('cy',0)
      .attr('r',m=>m.repo===d.ancestor.repo?4.5:3)
      .attr('fill',m=>color(m.repo))
      .attr('stroke',m=>m.repo===d.ancestor.repo?'#111':'#fff')
      .attr('stroke-width',m=>m.repo===d.ancestor.repo?2:1)
      .on('mousemove',(e,m)=>showTip(`<b>${m.repo}</b><br>${d.skill}<br>${m.first_date.slice(0,10)} · ${(m.stars||0).toLocaleString()}★${m.repo===d.ancestor.repo?'<br>⭐ ANCESTOR':''}`,e.clientX,e.clientY))
      .on('mouseout',hideTip);
  });
})();

// ---- Sankey ----
let sankeyDrawn=false;
function drawSankey(){
  if(sankeyDrawn) return; sankeyDrawn=true;
  const flows=LINEAGE.flows.slice(0,60);
  const names=[...new Set(flows.flatMap(f=>[f.from+' ▸',f.to]))];
  const idx=Object.fromEntries(names.map((n,i)=>[n,i]));
  const nodes=names.map(n=>({name:n}));
  const links=flows.map(f=>({source:idx[f.from+' ▸'],target:idx[f.to],value:f.count}));
  const W=Math.max(900,(document.body.clientWidth||1000)-56),H=Math.max(500,names.length*13);
  const svg=d3.select('#sankeysvg').attr('width',W).attr('height',H);svg.selectAll('*').remove();
  const sk=d3.sankey().nodeWidth(12).nodePadding(7).extent([[180,10],[W-180,H-10]])
    .nodeId(d=>d.index);
  let graph;try{graph=sk({nodes:nodes.map(d=>({...d})),links:links.map(d=>({...d}))});}
  catch(e){svg.append('text').attr('x',20).attr('y',30).text('sankey error: '+e);return;}
  const color=d3.scaleOrdinal(d3.schemeTableau10);
  svg.append('g').selectAll('rect').data(graph.nodes).join('rect')
    .attr('x',d=>d.x0).attr('y',d=>d.y0).attr('width',d=>d.x1-d.x0)
    .attr('height',d=>Math.max(1,d.y1-d.y0)).attr('fill',d=>color(d.name.split('/')[0]));
  svg.append('g').attr('fill','none').selectAll('path').data(graph.links).join('path')
    .attr('d',d3.sankeyLinkHorizontal()).attr('stroke',d=>color(d.source.name.split('/')[0]))
    .attr('stroke-opacity',.35).attr('stroke-width',d=>Math.max(1,d.width))
    .on('mousemove',(e,d)=>showTip(`<b>${d.source.name.replace(' ▸','')}</b> → <b>${d.target.name}</b><br>${d.value} skill(s) copied`,e.clientX,e.clientY))
    .on('mouseout',hideTip);
  svg.append('g').selectAll('text').data(graph.nodes).join('text')
    .attr('x',d=>d.x0<W/2?d.x1+5:d.x0-5).attr('y',d=>(d.y0+d.y1)/2).attr('dy','.35em')
    .attr('text-anchor',d=>d.x0<W/2?'start':'end').attr('font-size',9)
    .text(d=>d.name.length>34?d.name.slice(0,34)+'…':d.name);
}
</script></body></html>"""


def main():
    data = json.load(open(LIN))
    n_repos = len({m['repo'] for c in data['clusters'] for m in c['members']})
    html = (TEMPLATE
            .replace('__DATA__', json.dumps(data, separators=(',', ':')))
            .replace('__NREPOS__', str(n_repos)))
    OUT.write_text(html)
    print(f'wrote {OUT} ({len(html)//1024} KB, {len(data["clusters"])} clusters, '
          f'{len(data["nonobvious"])} non-obvious)')


if __name__ == '__main__':
    main()
