"""
curiosities.py — Surface the oddities. The point is to rouse the reader's
curiosity, not just tabulate: popular-but-undiscoverable repos, viral skills,
coercive tone, extremes, risky-without-guardrails, the rare good citizens,
delightful names, degraded copies, and what's new since last crawl.

Recomputes from the merged corpus + lineage + history each run, so it stays
current as the crawl grows. Writes docs/curiosities.md.

Usage:  python crawlers/curiosities.py
"""
import json
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from score_corpus import load_all_crawls
from skill_quality import score_skill

BASE = Path(__file__).parent.parent
Q = BASE / 'data' / 'skill_quality.json'
LIN = BASE / 'data' / 'lineage.json'
HIST = BASE / 'data' / 'skill_history.json'
SIB = BASE / 'data' / 'sibling_files.json'
OUT = BASE / 'docs' / 'curiosities.md'

COERCE = re.compile(r'\b(you MUST|NEVER|ALWAYS|not negotiable|you do not have a '
                    r'choice|under no circumstances|do NOT|MANDATORY|absolutely must)\b')
TAGS = re.compile(r'<(extremely-important|critical|subagent-stop|mandatory|forbidden|do-not)[ >/]', re.I)
DELIGHT = re.compile(r'caveman|yeet|patronum|goblin|wizard|ninja|loki|yolo|whisper|'
                     r'oracle|sentinel|chaos|deslop|gigachad|digital-brain|vibe', re.I)


def short(repo):
    return repo.split('/')[0]


def main():
    res = [x for x in load_all_crawls() if x.get('skill_md_content')]
    Qd = json.load(open(Q))
    skills = Qd['skills']
    repos = Qd['repos']
    lin = json.load(open(LIN)) if LIN.exists() else {'clusters': [], 'nonobvious': []}
    hist = json.load(open(HIST)) if HIST.exists() else None
    sib = json.load(open(SIB)) if SIB.exists() else {}
    qby = {(s['repo'], s['file_path']): s for s in skills}

    # raw-text passes
    coerce, tags, longest = [], [], (0, '')
    for x in res:
        md = x['skill_md_content']
        nm = x['file_path'].split('/')[-2] if '/' in x['file_path'] else x['file_path']
        ref = f'{short(x["repo_full_name"])}/{nm}'
        c = len(COERCE.findall(md))
        if c >= 8:
            coerce.append((c, ref))
        if TAGS.search(md):
            tags.append(ref)
        w = len(md.split())
        if w > longest[0]:
            longest = (w, ref)
    coerce.sort(reverse=True)

    L = ['# Curiosities — the oddities worth a second look\n',
         '_Auto-generated by `crawlers/curiosities.py` from the merged corpus '
         f'({len(res)} skills, {len(repos)} repos). Rerun after each crawl._\n']

    # 1. Popular but undiscoverable
    L.append('## ⭐ Popular but undiscoverable\n')
    L.append('High stars, but the skills barely say *when* to use them — the crowd '
             'rewarded the content, not the discoverability.\n')
    pop = [(rn, r) for rn, r in repos.items()
           if (r.get('stars') or 0) >= 2000 and r['pct_with_when'] < 40]
    pop.sort(key=lambda x: x[1]['pct_with_when'])
    for rn, r in pop[:6]:
        L.append(f'- **{rn}** — {r["stars"]:,}★ but only **{r["pct_with_when"]}%** '
                 f'of its {r["n_skills"]} skills carry a WHEN-trigger.')
    L.append('')

    # 2. Viral skills
    L.append('## 🦠 The most-copied skills\n')
    L.append('Same skill, many repos — the closest thing to a viral hit.\n')
    for c in sorted(lin['clusters'], key=lambda c: -c['n_repos'])[:6]:
        rs = sorted({m['repo'].split('/')[0] for m in c['members']})
        L.append(f'- **`{c["skill"]}`** — in {c["n_repos"]} repos ({", ".join(rs)})')
    L.append('')

    # 3. Non-obvious ancestor
    if lin.get('nonobvious'):
        L.append('## 🌱 Small origin, big spread\n')
        for n in lin['nonobvious'][:4]:
            L.append(f'- `{n["skill"]}` first appeared in **{n["ancestor_repo"]}** '
                     f'({n["ancestor_stars"]}★) — then surfaced in '
                     f'**{n["biggest_descendant"]}** ({n["descendant_stars"]:,}★).')
        L.append('')

    # 4. Coercive tone
    L.append('## 😤 Skills that yell at the model\n')
    L.append('Heavy "you MUST / NEVER / not negotiable" framing — the opposite of '
             "Anthropic's measured house style.\n")
    for c, ref in coerce[:6]:
        L.append(f'- **`{ref}`** — {c} coercive directives.')
    L.append('')

    # 5. Nonstandard tags
    if tags:
        L.append('## 🏷️ Invented control tags\n')
        L.append('Bespoke XML-ish tags (`<extremely-important>`, `<subagent-stop>`) '
                 'with no canonical precedent:\n')
        L.append('- ' + ', '.join(f'`{t}`' for t in dict.fromkeys(tags)) + '\n')

    # 6. Extremes
    L.append('## 📏 Extremes\n')
    most_sib = sorted(sib.items(), key=lambda kv: -len(kv[1]))[:1]
    most_code = max(skills, key=lambda s: s.get('body_words', 0))  # placeholder
    L.append(f'- **Longest skill:** `{longest[1]}` — {longest[0]:,} words in one '
             'SKILL.md (the corpus median is ~810).')
    if most_sib:
        k, v = most_sib[0]
        L.append(f'- **Deepest folder:** `{short(k.split(chr(9))[0])}/'
                 f'{k.split("/")[-2]}` — {len(v)}+ sibling files around one skill.')
    L.append('')

    # 7. High-stakes, no guardrails
    hsns = []
    for x in res:
        nm = x['file_path'].split('/')[-2] if '/' in x['file_path'] else x['file_path']
        r = score_skill(x['skill_md_content'], nm,
                        sib.get(f'{x["repo_full_name"]}\t{x["file_path"]}'))
        if 'high-stakes-no-safety' in r['flags']:
            hsns.append(f'{short(x["repo_full_name"])}/{nm}')
    L.append('## ⚠️ Risky, with no seatbelt\n')
    L.append(f'**{len(hsns)} skills** describe high-stakes work (deploy / delete / '
             'payments / secrets) with no visible validation, dry-run, or guard step. '
             'A few:\n')
    L.append('- ' + ', '.join(f'`{h}`' for h in hsns[:8]) + '\n')

    # 8. The rare good citizens
    anti = [s for s in skills if s.get('desc_has_when') and 'no-anti-trigger' not in s['flags']]
    L.append('## ✅ The 2% who say "when NOT to"\n')
    L.append(f'Only **{len(anti)} of {len(skills)}** skills include an anti-trigger '
             '(when *not* to fire). The rare good citizens:\n')
    L.append('- ' + ', '.join(f'`{short(s["repo"])}/{s["name"]}`' for s in anti[:8]) + '\n')

    # 9. Delightful names
    delight = sorted({s['name'] for s in skills if s['name'] and DELIGHT.search(s['name'])})
    L.append('## 🎭 Names that made me look\n')
    L.append('- ' + ', '.join(f'`{n}`' for n in delight[:18]) + '\n')

    # 10. Degraded copies — same skill, different score across repos
    L.append('## 🔀 Same skill, different grade\n')
    L.append('Copies that diverged — usually one repo kept the reference/script '
             'files and the copy dropped them, so the *identical* SKILL.md scores '
             'differently:\n')
    spread = []
    for c in lin['clusters']:
        scored = [(m['repo'], qby.get((m['repo'], m['path']), {}).get('overall'))
                  for m in c['members']]
        scored = [(r, s) for r, s in scored if s is not None]
        if len(scored) >= 2:
            hi = max(scored, key=lambda x: x[1]); lo = min(scored, key=lambda x: x[1])
            if hi[1] - lo[1] >= 8:
                spread.append((hi[1] - lo[1], c['skill'], hi, lo))
    for d, name, hi, lo in sorted(spread, reverse=True)[:5]:
        L.append(f'- **`{name}`** — {hi[1]} in {short(hi[0])} vs {lo[1]} in '
                 f'{short(lo[0])} (Δ{d:.0f}).')
    L.append('')

    # 11. What's new / changed (from history)
    if hist and hist.get('crawls'):
        latest = hist['crawls'][-1]
        d = hist['deltas'][latest]
        L.append(f'## 🆕 New since last crawl ({latest})\n')
        L.append(f'- **+{d["skills_added"]}** skills added, **{d["skills_changed"]}** '
                 f'changed, **{d["skills_removed"]}** removed.')
        if d['repos_added']:
            L.append(f'- New repos: {", ".join(d["repos_added"])}')
        if d['top_movers']:
            L.append('- Biggest quality movers: ' +
                     ', '.join(f'`{k.split(chr(9))[0].split("/")[0]}/{k.split("/")[-2]}` '
                               f'({dv:+.0f})' for k, dv in d['top_movers'][:5]))
        L.append('')

    OUT.write_text('\n'.join(L))
    print(f'wrote {OUT} ({len(L)} lines)')
    # echo the punchiest bits
    print(f'  coercive top: {coerce[0] if coerce else "—"}')
    print(f'  longest: {longest}')
    print(f'  anti-trigger writers: {len(anti)}; high-stakes-no-safety: {len(hsns)}')


if __name__ == '__main__':
    main()
