"""
gen_stats.py — The single source of truth for the study's headline numbers.

Reads the derived data and writes:
  data/corpus_stats.json   machine-readable canonical stats
  docs/STATS.md            an always-fresh headline snapshot the narrative docs
                           (and articles) can cite instead of hard-coding numbers

Run as the last data stage of the pipeline. Never hand-edit STATS.md.

Usage:  python crawlers/gen_stats.py
"""
import json
from pathlib import Path

BASE = Path(__file__).parent.parent
Q = BASE / 'data' / 'skill_quality.json'
HIST = BASE / 'data' / 'skill_history.json'
LIN = BASE / 'data' / 'lineage.json'
LEAD = BASE / 'data' / 'originator_leaderboard.json'
UNIQUE = BASE / 'data' / 'unique_counts.json'
OUT_JSON = BASE / 'data' / 'corpus_stats.json'
OUT_MD = BASE / 'docs' / 'STATS.md'


def main():
    Qd = json.load(open(Q))
    co = Qd['corpus']
    sigs = Qd['signatures']
    hist = json.load(open(HIST)) if HIST.exists() else {}
    lin = json.load(open(LIN)) if LIN.exists() else {}
    lead = json.load(open(LEAD)) if LEAD.exists() else []
    uniq = json.load(open(UNIQUE)) if UNIQUE.exists() else {}

    stats = {
        'n_skills': co['n_skills'],
        'n_repos': co['n_repos'],
        # unique-skill funnel from count_skills.py — the de-duplicated headline.
        'unique_skills': uniq.get('distinct_skills_near_dup'),
        'distinct_exact_bodies': uniq.get('distinct_exact_bodies'),
        'distinct_concepts': uniq.get('distinct_concepts'),
        'duplicate_share_pct': uniq.get('duplicate_share_pct'),
        'median_quality': co['median_quality'],
        'mean_quality': co['mean_quality'],
        'pct_with_when': co['pct_with_when'],
        'pct_with_anti_trigger': co.get('pct_with_anti_trigger'),
        'pct_uses_refs': co['pct_uses_refs'],
        'grade_dist': co['grade_dist'],
        'flag_freq': co['flag_freq'][:8],
        'signatures': {s: {'n_repos': v['n_repos'], 'n_skills': v['n_skills'],
                           'median_quality': v['median_quality'],
                           'pct_with_when': v['pct_with_when']}
                       for s, v in sigs.items()},
        'crawls': hist.get('crawls', []),
        'latest_delta': hist.get('deltas', {}).get(hist.get('crawls', [None])[-1]) if hist.get('crawls') else None,
        'dup_clusters': len(lin.get('clusters', [])),
        'top_originators': [(r['repo'], r['originator_score']) for r in lead[:5]],
    }
    OUT_JSON.write_text(json.dumps(stats, indent=1))

    g = stats['grade_dist']
    L = [f'# STATS — live corpus snapshot\n',
         '_Auto-generated by `crawlers/gen_stats.py`. **Do not hand-edit.** '
         'Narrative docs should cite these numbers; `check_docs.py` flags any that '
         'fall out of sync._\n',
         f"- **{stats['n_skills']:,} SKILL.md files** across **{stats['n_repos']} repos**, "
         f"{len(stats['crawls'])} crawl snapshots ({', '.join(stats['crawls'])})",
         (f"- **~{stats['unique_skills']:,} unique skills** after collapsing exact + "
          f"near-duplicate copies ({stats['duplicate_share_pct']}% of files are dups; "
          f"{stats['distinct_concepts']:,} distinct concepts) — see `count_skills.py`"
          if stats.get('unique_skills') else ''),
         f"- **Median quality {stats['median_quality']}/100** "
         f"(mean {stats['mean_quality']})",
         f"- **WHEN-trigger:** {stats['pct_with_when']}%  ·  "
         f"**anti-trigger:** {stats['pct_with_anti_trigger']}%  ·  "
         f"**uses reference links:** {stats['pct_uses_refs']}%",
         f"- **Grades:** A {g.get('A',0):,} · B {g.get('B',0):,} · C {g.get('C',0):,} "
         f"· D {g.get('D',0):,} · F {g.get('F',0):,}",
         f"- **Cross-repo duplicate clusters:** {stats['dup_clusters']}",
         '',
         '## Quality by signature\n',
         '| signature | repos | skills | median | % WHEN |',
         '|---|---|---|---|---|']
    for s, v in sorted(stats['signatures'].items(), key=lambda x: -x[1]['median_quality']):
        L.append(f"| {s} | {v['n_repos']} | {v['n_skills']:,} | "
                 f"{v['median_quality']} | {v['pct_with_when']:.0f}% |")
    L.append('\n## Top originators\n')
    for repo, sc in stats['top_originators']:
        L.append(f"- `{repo}` — {sc}")
    if stats['latest_delta']:
        d = stats['latest_delta']
        L.append(f"\n## Latest crawl delta ({stats['crawls'][-1]})\n")
        L.append(f"- +{d['skills_added']} added · {d['skills_changed']} changed · "
                 f"-{d['skills_removed']} removed"
                 + (f" · new repos: {', '.join(d['repos_added'])}" if d['repos_added'] else ''))
    OUT_MD.write_text('\n'.join(L) + '\n')
    print(f'wrote {OUT_JSON} and {OUT_MD}')
    print(f"  {stats['n_skills']} skills, {stats['n_repos']} repos, "
          f"median {stats['median_quality']}, WHEN {stats['pct_with_when']}%")


if __name__ == '__main__':
    main()
