"""
gen_conventions.py — What conventions the BEST practitioners actually adopted.

Empirical (not prescriptive): compares convention-adoption among the highest-
scoring repos (median >= ELITE_CUT, >= MIN_SKILLS) against everyone else, so the
study shows the house style the community's top repos converged on. Refreshes on
every pipeline run.

Writes data/conventions.json and docs/adopted-conventions.md.

Usage:  python crawlers/gen_conventions.py
"""
import json
import re
import sys
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from score_corpus import load_all_crawls
from skill_quality import parse_skill

BASE = Path(__file__).parent.parent
Q = BASE / 'data' / 'skill_quality.json'
SIB = BASE / 'data' / 'sibling_files.json'
OUT_JSON = BASE / 'data' / 'conventions.json'
OUT_MD = BASE / 'docs' / 'adopted-conventions.md'
ELITE_CUT = 85
MIN_SKILLS = 10


def measure(group, crawl, sib):
    n = 0
    c = Counter()
    fm_keys = Counter()
    for s in group:
        md = crawl.get((s['repo'], s['file_path']))
        if not md:
            continue
        n += 1
        p = parse_skill(md['skill_md_content'])
        f, b = p['frontmatter'], p['body']
        for k in f:
            fm_keys[k] += 1
        if 'license' in f: c['license'] += 1
        if 'metadata' in f: c['metadata'] += 1
        if any(k in f for k in ('allowed-tools', 'allowed_tools')): c['allowed_tools'] += 1
        if any(k in f for k in ('origin', 'source')): c['provenance_keys'] += 1
        sibs = sib.get(f"{s['repo']}\t{s['file_path']}", [])
        if any(re.search(r'(^|/)(reference|references)/', x) for x in sibs): c['ref_dir'] += 1
        if any(re.search(r'(^|/)scripts/', x) for x in sibs): c['scripts_dir'] += 1
        dirn = s['file_path'].split('/')[-2] if '/' in s['file_path'] else ''
        if f.get('name') == dirn: c['name_eq_dir'] += 1
        if re.search(r'^## ', b, re.M): c['headings'] += 1
        if '```' in b: c['code_example'] += 1
        if re.search(r'^\s*\d+\. ', b, re.M): c['numbered_steps'] += 1
    pct = {k: round(100 * v / n) if n else 0 for k, v in c.items()}
    pct['n'] = n
    pct['top_fm_keys'] = fm_keys.most_common(8)
    return pct


def main():
    Qd = json.load(open(Q))
    repos, skills = Qd['repos'], Qd['skills']
    sib = json.load(open(SIB)) if SIB.exists() else {}
    crawl = {(r['repo_full_name'], r['file_path']): r
             for r in load_all_crawls() if r.get('skill_md_content')}

    elite_repos = sorted([rn for rn, r in repos.items()
                          if r['median_quality'] >= ELITE_CUT and r['n_skills'] >= MIN_SKILLS],
                         key=lambda r: -repos[r]['median_quality'])
    elite = set(elite_repos)
    E = measure([s for s in skills if s['repo'] in elite], crawl, sib)
    R = measure([s for s in skills if s['repo'] not in elite], crawl, sib)

    rows = [
        ('`name` matches the folder slug', 'name_eq_dir'),
        ('Worked code example in body', 'code_example'),
        ("Delegates depth to a `reference/` dir", 'ref_dir'),
        ('Ships a `scripts/` dir', 'scripts_dir'),
        ('Declares a `license` key', 'license'),
        ('Uses a `metadata` block', 'metadata'),
        ('Numbered procedure steps', 'numbered_steps'),
        ('`allowed-tools` key (inverted!)', 'allowed_tools'),
        ('Carries `origin`/`source` provenance keys', 'provenance_keys'),
    ]
    out = {'elite_cut': ELITE_CUT, 'elite_repos': elite_repos,
           'elite': E, 'rest': R}
    OUT_JSON.write_text(json.dumps(out, indent=1))

    L = [f'# Adopted Conventions — what the best practitioners actually do\n',
         f'_Auto-generated by `crawlers/gen_conventions.py`. **Empirical**, not '
         f'prescriptive: convention-adoption among the **{len(elite_repos)} top '
         f'repos** (median ≥ {ELITE_CUT}, ≥ {MIN_SKILLS} skills; {E["n"]} skills) '
         f'vs everyone else ({R["n"]} skills)._\n',
         '| Convention | Best practitioners | Everyone else |',
         '|---|---|---|']
    for label, key in rows:
        L.append(f"| {label} | **{E.get(key,0)}%** | {R.get(key,0)}% |")
    L.append('')
    L.append('## What the top repos converged on\n')
    L.append('1. **`name` always equals the directory slug** — the sharpest '
             'distinguisher (near-universal among the best, ~⅔ elsewhere).')
    L.append('2. **Show, don\'t just tell** — a worked code example, not just headings.')
    L.append('3. **Progressive disclosure as a folder convention** — `reference/` for '
             'prose depth, `scripts/` for executable helpers (~2× the rest).')
    L.append('4. **Tidy, complete frontmatter** — `name` / `description` / `license` / '
             '`metadata`, and little else.\n')
    L.append('## The originator-vs-copier tell\n')
    L.append(f"Frontmatter keys each group sprouts:\n")
    L.append(f"- **Best practitioners:** "
             + ', '.join(f'`{k}`' for k, _ in E['top_fm_keys'][:5]))
    L.append(f"- **Everyone else:** "
             + ', '.join(f'`{k}`' for k, _ in R['top_fm_keys'][:6]))
    L.append('\nThe lower tier carries **`origin`/`source`** keys — copy-provenance '
             'breadcrumbs that mark aggregated content.\n')
    L.append('> **On `allowed-tools` (the inverted row).** Don\'t read this as a '
             'quality negative. `allowed-tools` restricts which tools a skill may '
             'invoke — a real safety/scoping feature. It is rare among the elite '
             'because the canonical repos write *capability* skills (create '
             'documents, design, art) that need broad access. It is common in the '
             'rest because **workflow / agent / command** skills (research '
             'pipelines, code-ops, slash-commands) restrict tools *on purpose* — and '
             'for those it is good practice. A high-quality repo, `flonat/claude-'
             'research` (median 85), uses it on 96% of its skills. The rule is: '
             '**declare `allowed-tools` when your skill takes actions; omit it when '
             'it produces content.**\n')
    L.append('## Caveat\n')
    L.append('Mild circularity: "best practitioners" is cut by the rubric\'s own '
             'median. But several signals here — `metadata` adoption, worked examples, '
             'the `origin`/`source` contrast, the inverted `allowed-tools` — aren\'t '
             'directly scored, so they independently corroborate a real house style.\n')
    L.append('## The best-practitioner repos\n')
    for rn in elite_repos:
        r = repos[rn]
        L.append(f"- `{rn}` — median {r['median_quality']}, "
                 f"{r['n_skills']} skills ({r['signature']})")
    OUT_MD.write_text('\n'.join(L) + '\n')
    print(f'wrote {OUT_JSON} and {OUT_MD}')
    print(f"  elite {E['n']} skills vs rest {R['n']}; "
          f"name_eq_dir {E['name_eq_dir']}% vs {R['name_eq_dir']}%")


if __name__ == '__main__':
    main()
