"""
originator_leaderboard.py — Who actually invents vs who copies.

Ranks repos by an **originator score** built from the lineage data:
  - ancestries: how many copied-skill clusters this repo is the ancestor of,
    weighted by spread (how many other repos carry the copy)
  - novel concepts: skill concepts that exist ONLY in this repo (nobody copied
    from elsewhere, and it isn't a copy of anyone) — original inventions
  - a "copy ratio": share of the repo's skills that are cross-repo duplicates
    (high = mostly aggregates other people's work)

Writes data/originator_leaderboard.json and docs/originators.md.

Usage:  python crawlers/originator_leaderboard.py
"""
import json
import re
import sys
from collections import defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from score_corpus import load_all_crawls

BASE = Path(__file__).parent.parent
Q = BASE / 'data' / 'skill_quality.json'
LIN = BASE / 'data' / 'lineage.json'
OUT_JSON = BASE / 'data' / 'originator_leaderboard.json'
OUT_MD = BASE / 'docs' / 'originators.md'

STOP = {'skill', 'using', 'with', 'for', 'the', 'and', 'pro', 'advanced'}


def concept(name):
    toks = [t for t in re.split(r'[-_\s]+', (name or '').lower())
            if t and t not in STOP]
    return ' '.join(sorted(toks))


def main():
    Qd = json.load(open(Q))
    skills = Qd['skills']
    repos = Qd['repos']
    lin = json.load(open(LIN)) if LIN.exists() else {'clusters': []}

    n_skills = defaultdict(int)
    for s in skills:
        n_skills[s['repo']] += 1

    # concept -> set of repos that have it (for novelty)
    concept_repos = defaultdict(set)
    repo_concepts = defaultdict(set)
    for s in skills:
        c = concept(s['name'])
        if c:
            concept_repos[c].add(s['repo'])
            repo_concepts[s['repo']].add(c)

    # which skills are part of a cross-repo duplicate cluster (copies)
    dup_keys = set()
    ancestor_credit = defaultdict(float)
    for c in lin['clusters']:
        member_repos = {m['repo'] for m in c['members']}
        for m in c['members']:
            dup_keys.add((m['repo'], m['path']))
        a = c.get('ancestor')
        if a and c.get('ancestor_basis') in ('canonical-authority', 'date-reliable'):
            # credit the ancestor, weighted by how far the skill spread
            ancestor_credit[a['repo']] += len(member_repos) - 1

    dup_by_repo = defaultdict(int)
    for (repo, path) in dup_keys:
        dup_by_repo[repo] += 1

    rows = []
    for repo, n in n_skills.items():
        novel = sum(1 for c in repo_concepts[repo] if len(concept_repos[c]) == 1)
        copies = dup_by_repo.get(repo, 0)
        anc = ancestor_credit.get(repo, 0)
        orig_rate = novel / n                       # fraction unique to this repo
        copy_frac = copies / n                       # fraction copied from elsewhere
        # Influence (others copy you) is the real originality signal and must not
        # be drowned by raw size; novelty counts as a RATE, copying as a penalty.
        score = round(anc * 5 + orig_rate * 20 - copy_frac * 20, 1)
        rows.append({
            'repo': repo, 'n_skills': n,
            'ancestor_credit': round(anc, 1),
            'novel_concepts': novel,
            'originality_rate': round(100 * orig_rate, 1),
            'copies_in': copies,
            'copy_ratio': round(100 * copy_frac, 1),
            'signature': repos.get(repo, {}).get('signature'),
            'stars': repos.get(repo, {}).get('stars'),
            'originator_score': score,
        })
    rows.sort(key=lambda r: -r['originator_score'])
    OUT_JSON.write_text(json.dumps(rows, indent=1))

    L = ['# Originators — who invents vs who copies\n',
         '_Auto-generated by `crawlers/originator_leaderboard.py`. Originator score '
         'rewards being the **ancestor** of copied skills (weighted by spread) and '
         '**novel concepts** (capabilities only you have), and penalises a high '
         '**copy ratio** (skills duplicated from elsewhere)._\n',
         '| # | repo | sig | ★ | originator score | copied-from (ancestor credit) | originality rate | copy ratio |',
         '|---|---|---|---|---|---|---|---|']
    for i, r in enumerate(rows[:18], 1):
        st = f"{r['stars']:,}" if r['stars'] else '—'
        L.append(f"| {i} | `{r['repo']}` | {r['signature']} | {st} | "
                 f"**{r['originator_score']}** | {r['ancestor_credit']} | "
                 f"{r['originality_rate']}% | {r['copy_ratio']}% |")
    L.append('')
    # the inverters: high stars but mostly copying
    copiers = sorted([r for r in rows if r['copy_ratio'] >= 15],
                     key=lambda r: -r['copy_ratio'])[:5]
    if copiers:
        L.append('## Mostly aggregators (high copy ratio)\n')
        for r in copiers:
            L.append(f"- **`{r['repo']}`** — {r['copy_ratio']}% of its "
                     f"{r['n_skills']} skills are cross-repo duplicates.")
        L.append('')
    L.append('_Notes: **ancestor credit** = clusters where this repo is the proven '
             'origin, weighted by spread (only trustworthy directions — canonical '
             'authority or clean commit dates — so it is conservative). **Copy ratio** '
             'counts skills that appear in >1 repo; for an origin repo like '
             '`anthropics/skills` that is high because it is *widely copied*, not '
             'because it copies — the dominant ancestor credit more than offsets the '
             'penalty. The takeaway: influence (being copied from) is what separates '
             'true originators from large aggregators._')
    OUT_MD.write_text('\n'.join(L))
    print(f'wrote {OUT_JSON} and {OUT_MD}')
    print('top originators:')
    for r in rows[:6]:
        print(f"  {r['originator_score']:6.1f}  {r['repo']:42s} "
              f"(novel {r['novel_concepts']}, anc {r['ancestor_credit']}, "
              f"copy {r['copy_ratio']}%)")


if __name__ == '__main__':
    main()
